### ISSUE TITLE
Issue with Cookies

### ISSUE THREAD

**Issue by PeterPilley** [Brutia/electron-keycloak-example#1]
Hi, thanks heaps for putting this code up, I am trying to test now but am seeing UnhandledPromiseRejectionWarning: Error: Setting cookie failed just wondering if you have solved this.

**Comment by PeterPilley** [comment]
Hi I solved this by changing to public from confidential

**Comment by Brutia** [comment]
Hi, thanks for your issue, and the solution! I've created this project for prototyping purposes. For now the keycloak login project is in standby, but I never had your problem, but still, it can be usefull
